<?php
/** @var \OmniPro\Blogv2\Block\Template $block */
?>

<div class="nuevopost">
    <h3>New blog post</h3>  
    <form class="formulariopost" action="" method="post">
        <div class="campospost">
            <input type="text" name="titulo" placeholder="My post title">
            <textarea class="contenidopost" name="contenido" value="Here all my important post text!"></textarea>
            <input type="email" name="email" placeholder="Email Address">
            <input type="text" name="img" placeholder="Imagen">
        </div>
        <div class="botonguardar">
            <button type="submit">Save post</button>
        </div>
    </form>
</div>