<?php
/** @var \OmniPro\Blog\Model\BlogViewModel $viewModel */
$viewModel = $block->getViewModel();
?>

<div class="container">
    <div class="encabezado">
        <h1 class="title">My spectacular blog!!</h1>
        <p>
            <?= $viewModel->getInfo(); ?>
        </p>
    </div>
    <div class="nuevopost">
        <h3>New blog post</h3>
        <form class="formulariopost" action="<?= $block->getUrl('blogview/index/save') ?>" method="post">
            <div class="campospost">
                <input type="text" name="titulo" placeholder="My post title">
                <textarea class="contenidopost" name="contenido" value="Here all my important post text!"></textarea>
                <input type="email" name="email" placeholder="Email Address">
                <input type="text" name="img" placeholder="Imagen">
                <!--<input type="file" name="">-->
            </div>
            <div class="botonguardar">
                <button type="submit">Save post</button>
            </div>
        </form>
    </div>
    <div class="listado-post">
        <?php foreach ($viewModel->getPost() as $post) : ?>
        <div class="post">
            <div class="seccion-a">
                <p class="post-titulo"><?= $post->getTitle(); ?></p>
                <p class="post-fecha">dd/mm/yyyy</p>
            </div>
            <div class="seccion-b">
                <div class="post-imagen">
                    <?= $post->getImg(); ?>
                </div>
                <div class="post-contenido">
                    <?= $post->getContent(); ?>
                </div>
            </div>
        </div>
        <?php endforeach ?>
    </div>
</div>
