<?php
/** @var \OmniPro\Blog\Model\BlogViewModel $viewModel */
$viewModel = $block->getViewModel();
?>

<div class="listado_post">
    <?php foreach($viewModel->getPost() as $post): ?>
    <div>
        <p><?= $post->getTitle(); ?></p>
    </div>
    <div>
        <p><?= $post->getContent(); ?></p>
    </div>
    <div>
        <p><?= $post->getImg(); ?></p>
    </div>
    <?php endforeach; ?>
</div>
</div>